More work-arounds for pinentry vs debconf lack of stdin

diff --git a/data/usr/sbin/grub-install b/data/usr/sbin/grub-install
--- a/data/usr/sbin/grub-install
+++ b/data/usr/sbin/grub-install
@@ -20,10 +20,20 @@
 # signature files, let GRUB go to a rescue prompt, and then turn off
 # check_signatures.
 
-set -e
 
 # Load debconf: used for prompting for passphrase.
 . /usr/share/debconf/confmodule
+
+KEYDIR=/etc/ubuntu-secure-boot/keys
+export GNUPGHOME="$KEYDIR"
+#tty=$(tty)
+#if [ $? -eq 0 ]
+#then
+#    export GPG_TTY=$(tty)
+#    gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
+#fi
+
+set -e
 
 runsbsign() {
     # On Ubuntu 16.04, sbsign crashes randomly; this appears to be a
@@ -52,21 +62,40 @@ EFI_FILENAME=securegrubx64.efi   # EFI image name
 BOOTLOADER_ID=ubuntu             # EFI directory on EFI partition
 FORMAT=x86_64-efi                # grub --format
 
-KEYDIR=/etc/ubuntu-secure-boot/keys
-export GNUPGHOME="$KEYDIR"
 
 # Temporary file cleanup
 Cleanup () {
-    if [ -n "$GPGPUBLICKEY" ] ; then
-        rm -f "$GPGPUBLICKEY"
-    fi
-    if [ -n "$GRUBSTAGE" ] ; then
-        rm -rf "$GRUBSTAGE"
-    fi
-    if [ -n "$PEMPRIVATEKEY" ] ; then
-        rm -f "$PEMPRIVATEKEY"
-    fi
+    [ -n "$GPGPUBLICKEY" ] && rm -f "$GPGPUBLICKEY" ]
+    [ -n "$GRUBSTAGE" ] && rm -rf "$GRUBSTAGE"
+    [ -n "$PEMPRIVATEKEY" ] && rm -f "$PEMPRIVATEKEY"
     [ -n "$NULL" ] && rm -f "$NULL"
+}
+
+GetPassphrase() {	
+    # Ask user for passphrase: note that we die if return code is 30,	
+    # indicating that the user won't be asked the question:	
+    db_settitle ubuntu-secure-boot/title	
+    db_reset ubuntu-secure-boot/passphrase	
+    db_fset ubuntu-secure-boot/passphrase seen false	
+    db_input critical ubuntu-secure-boot/passphrase	
+    db_go	
+    db_get ubuntu-secure-boot/passphrase	
+    PASSPHRASE="$RET"	
+    # Always reset the password so that it doesn't remain behind:	
+    db_reset ubuntu-secure-boot/passphrase	
+}	
+	
+# Ask if the user wants to retry entering passphrase:	
+RetryPassphrase() {	
+    db_settitle ubuntu-secure-boot/title	
+    db_reset ubuntu-secure-boot/retrypassphrase	
+    db_fset ubuntu-secure-boot/retrypassphrase seen false	
+    db_input critical ubuntu-secure-boot/retrypassphrase	
+    db_go	
+    db_get ubuntu-secure-boot/retrypassphrase	
+    if [ "$RET" != true ] ; then	
+        exit 1	
+    fi	
 }
 
 # Does key directory exist?
@@ -81,25 +110,54 @@ then
     NULL="$(mktemp)"
     trap Cleanup EXIT INT TERM
 
-    export GPG_TTY=$(tty)
 
     # See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838153
     # KEYID is not in output. So instead, export and grep it
     KEYID=$(gpg -a --export |gpg --list-packets --verbose | \
       awk '/Ubuntu secure boot EFI key/ { printing=1 } /keyid/ { if (printing) { print $NF; printing=0} } {}')
 
-    gpg --batch --yes --output "$GPGPUBLICKEY" --export "$KEYID"
+    gpg --yes --output "$GPGPUBLICKEY" --export "$KEYID"
 
-    gpg-connect-agent updatestartuptty /bye
-    
-    # Test signing to make sure passphrase is ok, also to
-    # fetch it into the gpg-agent cache
-    # We use a file for the output rather than /dev/null
-    # since it does a chmod 644 after its done!
-    until : | gpg --batch -u "$KEYID" -o "$NULL" -as -
+    set +e
+
+    PASSPHRASEOK=0
+    until [ $PASSPHRASEOK -eq 1 ]
     do
-	echo "Incorrect passphrase, retry"
+        : | gpg --pinentry-mode cancel --yes -u "$KEYID" -o "$NULL" -as - 2>/dev/null
+        if [ $? -eq 0 ]
+        then
+            PASSPHRASEOK=1
+        else
+            echo "get the passphrase"
+            GetPassphrase
+            echo "$PASSPHRASE" | gpg --batch --passphrase-fd 0 \
+                                      --pinentry-mode loopback --yes \
+                                      -u "$KEYID" -o "$NULL" -as /dev/null 2>/dev/null
+            if [ $? -eq 0 ]
+            then
+                PASSPHRASEOK=1
+            else
+                RetryPassphrase
+            fi
+        fi
     done
+    if [ $PASSPHRASEOK != 1 ]
+    then
+        echo "^C pressed, giving up"
+        exit 1
+    fi
+
+    set -e
+#    # Test signing to make sure passphrase is ok, also to
+#    # fetch it into the gpg-agent cache
+#    # We use a file for the output rather than /dev/null
+#    # since it does a chmod 644 after its done!
+#    until : | gpg --pinentry-mode ask --yes -u "$KEYID" -o "$NULL" -as -
+#    do
+#        rm -f "$NULL"
+#	echo "Incorrect passphrase, retry"
+#        sleep 1
+#    done
     rm -f "$NULL"
 
     # We have to sign all GRUB files (e.g. modules) with gpg.  Currently,
@@ -126,7 +184,7 @@ then
     # Sign GRUB files
     echo "Signing GRUB modules... (this will take a minute)"
     find "$GRUBSTAGE"/boot -type f -print0 | xargs -0 -n 1 \
-        gpg --yes --batch -u "$KEYID" --detach-sign
+        gpg -v --yes -u "$KEYID" --detach-sign
 
     # Make memdisk/tar image:
     echo "Creating memdisk..."
@@ -253,7 +311,11 @@ then
         $USED_MODULES
 
     # Save db.key OpenSSL key to an unencrypted file (remove passphrase):
-    openssl rsa -in "$KEYDIR/db.key" -out "$PEMPRIVATEKEY"
+    until echo "$PASSPHRASE" | openssl rsa -in "$KEYDIR/db.key" -out "$PEMPRIVATEKEY" -passin stdin
+    do
+        echo "Bad passphrase on ssl key"
+        sleep 1
+    done
 
     # Sign the EFI image into final output location.
     echo "Signing GRUB image..."
